export enum ErrorCode {
    NOT_FOUND = 'NOT_FOUND',
    USER_EXIST = 'USER_EXIST',
    EMAIL_EXIST = 'EMAIL_EXIST',
    DB_CONNECT_ERROR = 'DB_CONNECT_ERROR',
    NO_TOKEN_PROVIDED = 'NO_TOKEN_PROVIDED',
    UNAUTHORIZED = 'UNAUTHORIZED'
}
